[versions]
kotlin = "2.0.0"
shadowJar = "8.1.1"
utils = "1.3.9-RC2"
gson = "2.11.0"
kotlinx-coroutines = "1.8.1"
okio = "3.9.0"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
utils-gson = { module = "com.github.wdtve.utils:utils-gson", version.ref = "utils" }
utils-io = { module = "com.github.wdtve.utils:utils-io", version.ref = "utils" }
utils-io-okio = { module = "com.github.wdtve.utils:utils-io-okio", version.ref = "utils" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "kotlinx-coroutines" }
stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
stdlib-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }


[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }